### ISSUE TITLE
Issue with docker-compose yml file

### ISSUE THREAD

**Issue by walkero-gr** [moisei/mssql-server-linux#1]
Thank you for your fine work on this docker.
I have an issue with a docker-compose yml file and the SA_PASSWORD env vaiable. Although I set this in the yml file, and the docker works just fine, the password of the user sa remains the default you set in the DockerFile, and it doesn't change.

Have you ever had such issues before? Can this be solved somehow?

Thank you for your time.

**Comment by moisei** [comment]
I've concentrated on missing installations, so the password is just hardcoded.
You can either change the password, once container is up and running, or change Dockerfile, to use SA_PASSWORD  env, instead (push request would be appreciated :) )
